export enum REPOSITORIES {
  USER_REPOSITORY = 'USER_REPOSITORY',
  TOKEN_REPOSITORY = 'TOKEN_REPOSITORY',
  FILE_REPOSITORY = 'FILE_REPOSITORY',
  ROOM_REPOSITORY = 'ROOM_REPOSITORY',
}

export enum AUTHORIZATION {
  SALT_ROUNDS = 15,
}

export enum FILES {
  FILES_PATH = 'files/',
}

export const REFRESH_TOKEN = 'refresh_token';
